Repository Green-Software-Foundation/carbon-aware-sdk, pull requests merged in 2022-10, with the labels that each got.

#75 Add electricityMap plugin
  Dockerfile
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMap/src/CarbonAware.DataSources.ElectricityMap.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMap/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMap/src/ElectricityMapDataSource.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMap/src/InternalsVisibleTo.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMap/test/CarbonAware.DataSources.ElectricityMap.Tests.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMap/test/ElectricityMapDataSourceTests.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMap/test/LocationConverterTests.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.Registration/CarbonAware.DataSources.Registration.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.Registration/Configuration/DataSourceType.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.Registration/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/CarbonAware.Tools.ElectricityMapClient.csproj
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Configuration/ConfigurationException.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Configuration/ElectricityMapClientConfiguration.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Constants/AuthenticationHeaderTypes.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Constants/Paths.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Constants/QueryStrings.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/ElectricityMapClient.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/ElectricityMapClientException.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/ElectricityMapClientHttpException.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/IElectricityMapClient.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/InternalsVisibleTo.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Model/Forecast.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Model/GridEmissionDataPoint.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Model/LoginResult.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/Model/Zone.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/src/README.md
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/test/AssemblyInfo.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/test/CarbonAware.Tools.ElectricityMapClient.Tests.csproj
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/test/ElectricityMapClientTests.cs
  src/CarbonAware.Tools/CarbonAware.Tools.ElectricityMapClient/test/TestData.cs
  src/CarbonAware.WebApi/test/integrationTests/CarbonAware.WebApi.IntegrationTests.csproj
  src/CarbonAware.WebApi/test/integrationTests/IntegrationTestingBase.cs
  src/CarbonAware.WebApi/test/integrationTests/mocks/ElectricityMapDataSourceMocker.cs
  src/CarbonAwareSDK.sln
  src/electricityMap.runsettings
Labels: v1.1

#137 Bug/appsettings local fix
  .gitignore
  .vscode/launch.json
  GettingStarted.md
  src/CarbonAware.CLI/src/CarbonAware.CLI.csproj
  src/CarbonAware.CLI/src/Program.cs
  src/CarbonAware.CLI/src/Properties/launchSettings.json
  src/CarbonAware.CLI/src/appsettings.Development.json.template
  src/CarbonAware.WebApi/src/Program.cs
  src/CarbonAware.WebApi/src/appsettings.Development.json
  src/CarbonAware.WebApi/src/appsettings.Development.json.template
Labels: v1.0

#153 SDK as a C# Library ADR
  docs/architecture/decisions/0009-sdk-as-a-c#-client-library.md
Labels: ADR

#159 Packaging CarbonAware SDK ADR
  docs/architecture/decisions/0010-sdk-packaging.md
Labels: ADR

#147 Data Source Interfaces ADR
  docs/architecture/decisions/0007-data-source-interfaces.md
Labels: ADR
