Repository Green-Software-Foundation/carbon-aware-sdk, pull requests merged in 2022-11, with the labels that each got.

#154 Adding readmes for architecture diagrams
  docs/architecture/aggregators.md
  docs/architecture/data-sources.md
  docs/architecture/overview.md
  docs/carbon-aware-webapi.md
  docs/images/overview-tiers-swimlanes.png
  docs/images/tiers-architecture.drawio.png
  docs/images/webapi-swimlanes.png
  src/CarbonAware.Aggregators/src/CarbonAware/README.md
Labels: COP27

#157 Add multi-purpose Location Source
  GettingStarted.md
  docs/configuration.md
  src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareParameters.cs
  src/CarbonAware.Aggregators/test/CarbonAwareAggregatorTests.cs
  src/CarbonAware.Aggregators/test/CarbonAwareParametersTests.cs
  src/CarbonAware.Aggregators/test/TestData.cs
  src/CarbonAware.CLI/src/CarbonAwareCLI.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/JsonDataSource.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.Json/test/JsonDataSourceTests.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/CarbonAware.DataSources.WattTime.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/WattTimeDataSourceTests.cs
  src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/src/AzureLocationSource.cs
  src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/src/CarbonAware.LocationSources.Azure.csproj
  src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/src/azure-regions.json
  src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/test/AzureLocationSourceTest.cs
  src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/test/TestConstants.cs
  src/CarbonAware.LocationSources/src/CarbonAware.LocationSources.csproj
  src/CarbonAware.LocationSources/src/Configuration/LocationDataSourcesConfiguration.cs
  src/CarbonAware.LocationSources/src/Configuration/LocationSourceFile.cs
  src/CarbonAware.LocationSources/src/LocationSource.cs
  src/CarbonAware.LocationSources/test/AssemblyInfo.cs
  src/CarbonAware.LocationSources/test/CarbonAware.LocationSources.Test.csproj
  src/CarbonAware.LocationSources/test/LocationSourceFileTests.cs
  src/CarbonAware.LocationSources/test/LocationSourceTest.cs
  src/CarbonAware.LocationSources/test/TestConstants.cs
  src/CarbonAware.WebApi/src/Models/EmissionsForecastDTO.cs
  src/CarbonAware.WebApi/test/unitTests/models/EmissionsForecastDTOTests.cs
  src/CarbonAware/src/Interfaces/ILocationSource.cs
  src/CarbonAware/src/Model/EmissionsForecast.cs
  src/CarbonAware/src/Model/Location.cs
  src/CarbonAware/src/Model/LocationEnums.cs
  src/CarbonAware/test/model/LocationTests.cs
  src/CarbonAwareSDK.sln
  src/data/location-sources/azure-regions.json
Labels: COP27

#184 Add ADR-0011. CD pipeline for release process
  docs/architecture/decisions/0011-cd-pipeline.md
Labels: ADR

#127 ADR-005 Using IAsyncEnumerable to stream large responses
  docs/architecture/decisions/0005-IAsyncEnumerable-HttpResponseExceptionFilter.md
Labels: ADR

#187 Refactor data source interfaces
  src/CarbonAware.Aggregators/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.Aggregators/src/Emissions/EmissionsAggregator.cs
  src/CarbonAware.Aggregators/src/Emissions/IEmissionsAggregator.cs
  src/CarbonAware.Aggregators/src/Forecast/ForecastAggregator.cs
  src/CarbonAware.Aggregators/src/Forecast/IForecastAggregator.cs
  src/CarbonAware.Aggregators/test/EmissionsAggregatorTests.cs
  src/CarbonAware.Aggregators/test/ForecastAggregatorTests.cs
  src/CarbonAware.CLI/src/Commands/Emissions/EmissionsCommand.cs
  src/CarbonAware.CLI/src/Commands/EmissionsForecasts/EmissionsForecastsCommand.cs
  src/CarbonAware.CLI/test/unitTests/Commands/Emissions/EmissionsCommandTests.cs
  src/CarbonAware.CLI/test/unitTests/Commands/EmissionsForecasts/EmissionsForecastsComandTests.cs
  src/CarbonAware.CLI/test/unitTests/TestBase.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/JsonDataSource.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.Registration/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs
  src/CarbonAware.WebApi/src/Controllers/CarbonAwareController.cs
  src/CarbonAware.WebApi/test/unitTests/CarbonAwareControllerTests.cs
  src/CarbonAware.WebApi/test/unitTests/TestsBase.cs
  src/CarbonAware/src/Interfaces/ICarbonIntensityDataSource.cs
  src/CarbonAware/src/Interfaces/IEmissionsDataSource.cs
  src/CarbonAware/src/Interfaces/IForecastDataSource.cs
  src/CarbonAware/src/NullEmissionsDataSource.cs
  src/CarbonAware/src/NullForecastDataSource.cs
Labels: COP27

#185 160/library routes forecast and average
  GettingStarted.md
  docs/architecture/c#-client-library.md
  docs/gsf-carbon-aware-library-package.md
  src/CarbonAware.Tools/CarbonAware.Tools.WattTimeClient/src/WattTimeClientException.cs
  src/CarbonAwareSDK.sln
  src/GSF.CarbonAware/src/Configuration/ServiceCollectionExtensions.cs
  src/GSF.CarbonAware/src/Exceptions/CarbonAwareException.cs
  src/GSF.CarbonAware/src/GSF.CarbonAware.csproj
  src/GSF.CarbonAware/src/Handlers/EmissionsHandler.cs
  src/GSF.CarbonAware/src/Handlers/ForecastHandler.cs
  src/GSF.CarbonAware/src/Handlers/IEmissionsHandler.cs
  src/GSF.CarbonAware/src/Handlers/IForecastHandler.cs
  src/GSF.CarbonAware/src/Models/EmissionsData.cs
  src/GSF.CarbonAware/src/Models/EmissionsForecast.cs
  src/GSF.CarbonAware/test/EmissionsHandlerTests.cs
  src/GSF.CarbonAware/test/ForecastHandlerTests.cs
  src/GSF.CarbonAware/test/GSF.CarbonAware.Tests.csproj
Labels: bug, Ready for Review
