Repository Green-Software-Foundation/carbon-aware-sdk, pull requests merged in 2023-07, with the labels that each got.

#361 Devops/clean up workflows
  .github/workflows/0-stale.yml
  .github/workflows/1-pr.yaml
  .github/workflows/2-pre-release.yaml
  .github/workflows/2.a-deploy.yaml
  .github/workflows/build-cli-dotnet.yaml
  .github/workflows/build-packages.yaml
  .github/workflows/build-webapi.yaml
  .github/workflows/codeQL-analysis.yaml
  .github/workflows/dev_carbon-aware-api.yml
  .github/workflows/linting.yaml
  .github/workflows/run-sdkCLI-githubaction.yml
Labels: devops

#347 Skip deploy workflows in forked repos
  .github/workflows/2-pre-release.yaml
  .github/workflows/dev_carbon-aware-api.yml
Labels: for discussion, devops

#371 1.1.0 CHANGELOG Updates
  CHANGELOG.md
Labels: v1.1
