Repository Green-Software-Foundation/carbon-aware-sdk, pull requests merged in 2024-04, with the labels that each got.

#498 [URGENT] WebAPI container has not built due to segmentation fault
  .github/workflows/2-pre-release.yaml
  .github/workflows/4-release.yaml
  src/CarbonAware.WebApi/src/Dockerfile
  src/GSF.CarbonAware/src/GSF.CarbonAware.csproj
Labels: devops

#494 Fix typos
  README.md
  casdk-docs/docs/overview/adopters.md
  casdk-docs/docs/overview/contributing.md
  casdk-docs/docs/overview/enablement.md
  casdk-docs/docs/overview/overview.md
  casdk-docs/docs/quickstart.md
Labels: documentation

#500 Up Helm chart version to 1.2.0
  helm-chart/Chart.yaml
Labels: v1.4
