Repository Green-Software-Foundation/carbon-aware-sdk, pull requests merged in 2024-02, with the labels that each got.

#431 Update documentation of Usefulness (adopters.md)
  docs/adopters.md
Labels: Ready for Review, 1.3

#441 Draft of enablement.md
  docs/enablement.md
Labels: Ready for Review

#459 Readme updates for clarity
  README.md
  images/SOGS_banner1.png
  images/carbon-aware-software.png
  images/hackathon-banner.jpg
  images/screenshot_web_api.png
  images/types-of-green-software.png
  images/what-is-green-software.avif
Labels: documentation, 1.3

#461 CarbonHack24 Update to README.md
  README.md
Labels: vNext, 1.3

#464 Create SECURITY.md
  SECURITY.md
Labels: Ready for Review, 1.3

#454 Update quickstart.md
  docs/quickstart.md
Labels: 1.3

#453 Update overview.md
  docs/overview.md
Labels: 1.3

#449 Support location source setting in Helm chart
  docs/overview.md
  helm-chart/Chart.yaml
  helm-chart/templates/configmap.yaml
  helm-chart/templates/deployment.yaml
  helm-chart/values.yaml
  src/CarbonAware.LocationSources/src/LocationSource.cs
Labels: 1.3

#420 Migrating Azure Functions sample to isolated worker model
  samples/azure/azure-function/Dockerfile
  samples/azure/azure-function/GetCarbonIntensity.cs
  samples/azure/azure-function/GetForecast.cs
  samples/azure/azure-function/Program.cs
  samples/azure/azure-function/README.md
  samples/azure/azure-function/Startup.cs
  samples/azure/azure-function/function.csproj
Labels: vNext, Ready for Review

#470 Readme updated links to images
  README.md
Labels: Ready for Review
