Repository Green-Software-Foundation/carbon-aware-sdk, pull requests merged in 2024-03, with the labels that each got.

#475 Release 1.3 changelog
  CHANGELOG.md
Labels: Ready for Review

#404 Upgrade to .NET 8.0
  .devcontainer/Dockerfile
  .github/workflows/1-pr.yaml
  .github/workflows/dev_carbon-aware-api.yml
  .vscode/launch.json
  casdk-docs/docs/overview/overview.md
  casdk-docs/docs/quickstart.md
  casdk-docs/docs/tutorial-basics/carbon-aware-webapi.md
  casdk-docs/docs/tutorial-basics/containerization.md
  casdk-docs/docs/tutorial-extras/configuration.md
  casdk-docs/docs/tutorial-extras/packaging.md
  global.json
  helm-chart/templates/deployment.yaml
  helm-chart/values.yaml
  samples/lib-integration/ConsoleApp/ConsoleApp.csproj
  src/CarbonAware.CLI/src/CarbonAware.CLI.csproj
  src/CarbonAware.CLI/src/Dockerfile
  src/CarbonAware.CLI/test/integrationTests/CarbonAware.CLI.IntegrationTests.csproj
  src/CarbonAware.CLI/test/unitTests/CarbonAware.CLI.UnitTests.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/mock/CarbonAware.DataSources.ElectricityMaps.Mocks.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/CarbonAware.DataSources.ElectricityMaps.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/CarbonAware.DataSources.ElectricityMaps.Tests.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMapsFree/mock/CarbonAware.DataSources.ElectricityMapsFree.Mocks.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMapsFree/src/CarbonAware.DataSources.ElectricityMapsFree.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMapsFree/test/CarbonAware.DataSources.ElectricityMapsFree.Tests.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.Json/mock/CarbonAware.DataSources.Json.Mocks.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.Json/src/CarbonAware.DataSources.Json.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.Json/test/CarbonAware.DataSources.Json.Tests.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.Registration/CarbonAware.DataSources.Registration.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/mock/CarbonAware.DataSources.WattTime.Mocks.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/CarbonAware.DataSources.WattTime.csproj
  src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/test/CarbonAware.DataSources.WattTime.Tests.csproj
  src/CarbonAware.LocationSources/src/CarbonAware.LocationSources.csproj
  src/CarbonAware.LocationSources/test/CarbonAware.LocationSources.Test.csproj
  src/CarbonAware.Tools/CarbonAware.Tools.AWSRegionTestDataGenerator/CarbonAware.Tools.AWSRegionTestDataGenerator.csproj
  src/CarbonAware.Tools/CarbonAware.Tools.AzureRegionTestDataGenerator/CarbonAware.Tools.AzureRegionTestDataGenerator.csproj
  src/CarbonAware.WebApi/src/.config/dotnet-tools.json
  src/CarbonAware.WebApi/src/CarbonAware.WebApi.csproj
  src/CarbonAware.WebApi/src/Dockerfile
  src/CarbonAware.WebApi/src/Program.cs
  src/CarbonAware.WebApi/test/integrationTests/CarbonAware.WebApi.IntegrationTests.csproj
  src/CarbonAware.WebApi/test/unitTests/CarbonAware.WebApi.UnitTests.csproj
  src/CarbonAware/src/CarbonAware.csproj
  src/CarbonAware/test/CarbonAware.Tests.csproj
  src/GSF.CarbonAware/src/GSF.CarbonAware.csproj
  src/GSF.CarbonAware/src/GSF.CarbonAware.targets
  src/GSF.CarbonAware/test/GSF.CarbonAware.Tests.csproj
  src/clients/docker-generate-clients.sh
  src/clients/generate-clients.sh
  src/clients/tests/csharp/Dockerfile
  src/clients/tests/csharp/csharp.csproj
Labels: vNext, Ready for Review

#421 Add cache functionality for emissions data
  casdk-docs/docs/tutorial-extras/configuration.md
  src/CarbonAware.DataSources/CarbonAware.DataSources.Registration/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware/src/Configuration/EmissionsDataCacheConfiguration.cs
  src/CarbonAware/src/Configuration/EmissionsDataCacheConfigurationExtensions.cs
  src/CarbonAware/src/Proxies/Cache/LatestEmissionsCache.cs
  src/CarbonAware/test/CarbonAware.Tests.csproj
  src/CarbonAware/test/Configuration/EmissionsDataCacheConfigurationTests.cs
  src/CarbonAware/test/Proxy/Cache/LatestEmissionsCacheTests.cs
Labels: Ready for Review

#422 Add Prometheus exporter
  casdk-docs/docs/tutorial-extras/configuration.md
  src/CarbonAware.WebApi/src/CarbonAware.WebApi.csproj
  src/CarbonAware.WebApi/src/Configuration/CarbonExporterConfiguration.cs
  src/CarbonAware.WebApi/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.WebApi/src/Metrics/CarbonMetrics.cs
  src/CarbonAware.WebApi/src/Metrics/MetricsResourceDetector.cs
  src/CarbonAware.WebApi/src/Program.cs
  src/CarbonAware.WebApi/test/integrationTests/CarbonAwareControllerTests.cs
  src/CarbonAware.WebApi/test/integrationTests/IntegrationTestingBase.cs
  src/CarbonAware.WebApi/test/unitTests/Configuration/CarbonExporterConfigurationTests.cs
  src/CarbonAware.WebApi/test/unitTests/Configuration/ServiceCollectionExtensionsTests.cs
  src/CarbonAware/src/CarbonAwareVariablesConfiguration.cs
  src/GSF.CarbonAware/src/Configuration/ServiceCollectionExtensions.cs
Labels: vNext
