Repository Green-Software-Foundation/carbon-aware-sdk, pull requests merged in 2024-11, with the labels that each got.

#531 Add configuration for tracing log
  casdk-docs/docs/tutorial-extras/configuration.md
  src/CarbonAware.WebApi/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.WebApi/src/Program.cs
  src/CarbonAware.WebApi/test/unitTests/Configuration/ServiceCollectionExtensionsTests.cs
  src/CarbonAware/src/CarbonAwareVariablesConfiguration.cs
Labels: Ready for Review, v1.6.2

#587 Release 1.6.1
  CHANGELOG.md
  casdk-docs/docs/tutorial-extras/configuration.md
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/ElectricityMapsDataSource.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/Model/HistoryCarbonIntensityData.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/Client/ElectricityMapsClientTests.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/Client/TestData.cs
  src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/test/ElectricityMapsDataSourceTests.cs
  src/CarbonAware.WebApi/src/Configuration/ServiceCollectionExtensions.cs
  src/CarbonAware.WebApi/src/Program.cs
  src/CarbonAware.WebApi/test/unitTests/Configuration/ServiceCollectionExtensionsTests.cs
  src/CarbonAware/src/CarbonAwareVariablesConfiguration.cs
Labels: v1.6.1

#588 Add gh cli to devcontainer/codespace
  .devcontainer/devcontainer.json
Labels: Ready for Review, v1.7
